---
- name: Exo 29 utiliser les boucles
  hosts: all
  become: true

  vars:
    utilisateurs: [Abir, Milhane, Naen, Djibi]
  tasks:
  - name: CrÃ©er utilisateurs
    user:
      name: "{{ item }}"
    with_items: "{{ utilisateurs }}"