---
- hosts: client1
  become: yes

  tasks:
    - name: Cr√©er le script /root/script1.sh
      copy:
        dest: /root/script1.sh
        content: |
          #!/bin/bash
          touch /root/test1
        mode: '0755'
