---
- name: exo 4 et 6 installer et demarrer apache
  hosts: client3, client4

  tasks:
    - name: installer apache
      dnf:
        update_cache: true
        name: httpd
        state: present

    - name: d√©marre apache
      service:
        name: httpd
        state: started
